# Generated by Django 6.0.5 on 2026-05-06 01:00

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('libros', 'Libros'), ('ropa', 'Ropa'), ('utiles', 'Útiles'), ('electronica', 'Electrónica'), ('muebles', 'Muebles'), ('otros', 'Otros')], max_length=30)),
                ('tipo_intercambio', models.CharField(choices=[('intercambio', 'Intercambio'), ('venta', 'Venta'), ('regalo', 'Regalo')], max_length=20)),
                ('precio_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_articulo', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('seminuevo', 'Seminuevo')], default='usado', max_length=20)),
                ('estado_publicacion', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='activa', max_length=20)),
                ('imagenes', models.JSONField(blank=True, default=list)),
                ('autor', models.JSONField(default=dict)),
                ('ubicacion_entrega', models.CharField(blank=True, max_length=150, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
