# Generated by Django 6.0.5 on 2026-05-11 21:40

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.JSONField(default=dict)),
                ('usuario', models.JSONField(default=dict)),
                ('texto', models.CharField(max_length=300)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('visible', 'Visible'), ('oculto', 'Oculto')], default='visible', max_length=20)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentarios',
                'ordering': ['-fecha_comentario'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.JSONField(default=dict)),
                ('publicacion', models.JSONField(default=dict)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favoritos',
                'ordering': ['-fecha_agregado'],
            },
        ),
    ]
