# Generated by Django 6.0.5 on 2026-05-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha_comentario'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='favorito',
            options={'ordering': ['-fecha_agregado'], 'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
    ]
