# Generated by Django 6.0.5 on 2026-05-06 01:00

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudIntercambio',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.JSONField(default=dict)),
                ('solicitante', models.JSONField(default=dict)),
                ('mensaje', models.TextField()),
                ('propuesta_intercambio', models.TextField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
